version: '2'

services:

    nginx:
        container_name: WhiskyNginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "8091:80"
            - "444:443"
        volumes_from:
            - appdata
        environment:
            VIRTUAL_HOST: "whi.sky"
            NGINX_CONF: "dev"
        depends_on:
            - php-fpm
        links:
            - "php-fpm:WhiskyPHP"

    php-fpm:
        container_name: WhiskyPHP
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes_from:
            - appdata
        depends_on:
          - mysql
          - beanstalkd
          - appdata
        links:
          - "mysql:WhiskyMysql"
          - "beanstalkd:WhiskyBeanstalkd"

    appdata:
        container_name: WhiskyApp
        build:
            context: .
            dockerfile: docker/appdata/Dockerfile
        #image: vasildakov/tms:latest
        volumes:
            - ./appcode:/var/www/html

    mysql:
        container_name: WhiskyMysql
        image: mysql:5.7
        restart: always
        #build:
        #    context: .
        #    dockerfile: docker/mysql/Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: '1'
            MYSQL_DATABASE: 'whisky'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: '1'
        ports:
            - "3311:3306"

    redis:
        container_name: WhiskyRedis
        image: redis:3.2.0
        ports:
            - "6380:6379"

    beanstalkd:
        container_name: WhiskyBeanstalkd
        image: schickling/beanstalkd
        ports:
            - "11300:11300"