# Domain.Distillery.dcm.yml
Domain\Distillery:
  type: entity
  table: Distillery

  indexes:
    name_index:
      columns: [ name ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 50